"""initial_tables

Revision ID: 85b8af9ad26f
Revises: 
Create Date: 2026-05-22 07:28:03.309884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85b8af9ad26f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='finance', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_kind', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uploaded_files_kind_status', 'uploaded_files', ['file_kind', 'processing_status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('name_of_company', sa.String(length=500), nullable=True),
    sa.Column('address_of_company', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=200), nullable=True),
    sa.Column('invoice_number_normalized', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('account_details', sa.Text(), nullable=True),
    sa.Column('internal_note_description', sa.Text(), nullable=True),
    sa.Column('client_employee_related', sa.String(length=500), nullable=True),
    sa.Column('paid_at_date', sa.Date(), nullable=True),
    sa.Column('paid_by', sa.String(length=300), nullable=True),
    sa.Column('fixed_status', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('review_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('match_status', sa.String(length=50), server_default='unmatched', nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('ix_invoices_invoice_number_normalized', 'invoices', ['invoice_number_normalized'], unique=False)
    op.create_index('ix_invoices_match_status', 'invoices', ['match_status'], unique=False)
    op.create_index('ix_invoices_paid_at_date', 'invoices', ['paid_at_date'], unique=False)
    op.create_index('ix_invoices_review_status', 'invoices', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_review_status', table_name='invoices')
    op.drop_index('ix_invoices_paid_at_date', table_name='invoices')
    op.drop_index('ix_invoices_match_status', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number_normalized', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_uploaded_files_kind_status', table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
